# Generated by Django 5.1 on 2024-10-19 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changed', models.IntegerField()),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('ADDITION', 'Stock Addition'), ('REMOVAL', 'Stock Removal'), ('SOLD OUT', 'Sold Out'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('DISPOSAL', 'Disposal')], max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_APP.product')),
            ],
        ),
    ]
